### ISSUE TITLE
should rename library module name from majifix to library

### ISSUE THREAD

**Issue by lykmapipo** [CodeTanzania/open311-android-library#23]
It is well adopted as convection that a library project especially android one will have a module named `library` if it expose only single library. If that is a case lets rename `majifix` to `library` unless we plan to have more that one libraries within `open311-android-library` i.e `open311-android-core`, `open311-android-ui` etc.

**Comment by krtonga** [comment]
Module name has been updated to `library-core` and empty `library-ui` created. See PR for: `feature/package-name-and-ui-library` or commit: 0aba04f.
