### ISSUE TITLE
should rename package name to com.github.codetanzania.open311.android.library

### ISSUE THREAD

**Issue by lykmapipo** [CodeTanzania/open311-android-library#25]
Sure we can derive other convection. The mostly used in java and git is

1. Library `group` should be `com.github.<owner or organization>` i.e `com.github.codetanzania`
2. Package name should be `com.github.<owner or organization>:<project name>` i.e
`com.github.codetanzania.android.library`
3. On dependency
 * Add jipack to your root level build.gradle
 ```js
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}
```
* Then add dependency to a project as per jitpack specification
```js
dependencies {
    compile 'com.github.codetanzania:android-library:latest'
}
```

**Comment by krtonga** [comment]
Package name has been updated. See PR for: `feature/package-name-and-ui-library` or commit: 0aba04f1fe0c677a0ad1f8367f6ed08d2d962eb9.

Jitpack was added in a previous commit.
